minimum_pre_commit_version: 2.8.0
default_stages: [commit, push, manual]
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 98c88b23b7ea9a42f920adc1d7c8790f39772021
    hooks:
      - id: check-added-large-files
        args: [--maxkb=800]
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-ast
      - id: check-case-conflict
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: requirements-txt-fixer
